name: CI/CD Pipeline

on:
  push:
      branches:
        -main

jobs:
  deploy:
    runs-on: ubuntu-latest
  
  steps:
  - name: Checkout Code
    uses: actions/checkout@v3

  - name: Install SSH Key
    run: |
      mkdir -p ~/.ssh
      echo "${{ secrets.EC@_KEY }}" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa

  - name: Copy Files to EC2
    run: |
      ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      scp -r ./ ec2-user@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/app

  - name: Deploy on EC2
    run: |
      ssh ec2-user@${{ secrets.EC2_HOST }}"
        cd /home/${{ secrets.EC2_USER }}/app &&
        npm i &&
        npm run build &&
        pm2 restart all
      "